services:
  - type: web
    name: luminous-app
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npx vite preview --port $PORT --host 0.0.0.0
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18
    staticPublishPath: ./dist